apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/name: podmonitor
    app.kubernetes.io/instance: daemon-metrics-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: kube-dtn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: kube-dtn
  name: daemon-metrics-monitor
spec:
  podMetricsEndpoints:
    - path: /metrics
      port: http
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: daemon
