# permissions for end users to view topologies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: topology-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-dtn
    app.kubernetes.io/part-of: kube-dtn
    app.kubernetes.io/managed-by: kustomize
  name: topology-viewer-role
rules:
- apiGroups:
  - y-young.github.io
  resources:
  - topologies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - y-young.github.io
  resources:
  - topologies/status
  verbs:
  - get
