# permissions for end users to view routes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: route-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dtn-satellite-sdn
    app.kubernetes.io/part-of: dtn-satellite-sdn
    app.kubernetes.io/managed-by: kustomize
  name: route-viewer-role
rules:
- apiGroups:
  - sdn.dtn-satellite-sdn
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sdn.dtn-satellite-sdn
  resources:
  - routes/status
  verbs:
  - get
