---
apiVersion: v1
kind: List
items:
  - apiVersion: y-young.github.io/v1
    kind: Topology
    metadata:
      name: r1
    spec:
      links:
        - uid: 1
          peer_pod: r2
          local_intf: eth1
          peer_intf: eth1
          local_ip: 12.12.12.1/24
          peer_ip: 12.12.12.2/24
        - uid: 2
          peer_pod: r3
          local_intf: eth2
          peer_intf: eth1
          local_ip: 13.13.13.1/24
          peer_ip: 13.13.13.3/24
  - apiVersion: y-young.github.io/v1
    kind: Topology
    metadata:
      name: r2
    spec:
      links:
        - uid: 1
          peer_pod: r1
          local_intf: eth1
          peer_intf: eth1
          local_ip: 12.12.12.2/24
          peer_ip: 12.12.12.1/24
        - uid: 3
          peer_pod: r3
          local_intf: eth2
          peer_intf: eth2
          local_ip: 23.23.23.2/24
          peer_ip: 23.23.23.3/24
  - apiVersion: y-young.github.io/v1
    kind: Topology
    metadata:
      name: r3
    spec:
      links:
        - uid: 2
          peer_pod: r1
          local_intf: eth1
          peer_intf: eth2
          local_ip: 13.13.13.3/24
          peer_ip: 13.13.13.1/24
        - uid: 3
          peer_pod: r2
          local_intf: eth2
          peer_intf: eth2
          local_ip: 23.23.23.3/24
          peer_ip: 23.23.23.2/24
  - apiVersion: v1
    kind: Pod
    metadata:
      name: r1
      labels:
        test: 3node
    spec:
      containers:
        - image: alpine
          name: pod
          command: ["/bin/sh", "-c", "sleep 2000000000000"]
  - apiVersion: v1
    kind: Pod
    metadata:
      name: r2
      labels:
        test: 3node
    spec:
      containers:
        - image: alpine
          name: pod
          command: ["/bin/sh", "-c", "sleep 2000000000000"]
  - apiVersion: v1
    kind: Pod
    metadata:
      name: r3
      labels:
        test: 3node
    spec:
      containers:
        - image: alpine
          name: pod
          command: ["/bin/sh", "-c", "sleep 2000000000000"]
