apiVersion: sdn.dtn-satellite-sdn/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: route
    app.kubernetes.io/instance: route-sample
    app.kubernetes.io/part-of: dtn-satellite-sdn
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dtn-satellite-sdn
  name: route-sample
spec:
  # TODO(user): Add fields here
